### ISSUE TITLE
unhashable type: 'dict'

### ISSUE THREAD

**Issue by mnijres** [allyomalley/LiveTargetsFinder#5]
Hi, I am facing this problem with this cool tool LiveTargetFinder

Unfortunately when firing the tool i have this error:

![Screenshot from 2020-05-03 14-18-05](https://user-images.githubusercontent.com/61706378/80922211-7f887600-8d49-11ea-9d2b-0be9d01ad5cf.png)

**Comment by harmeet-1337** [comment]
its already solved here https://github.com/allyomalley/LiveTargetsFinder/issues/3

**Comment by mnijres** [comment]
Solved:
cd massdns
git checkout 65331fb528755621650a0fbacff12102cfdcdde9  ##add this line into file after cd massdns
![solved](https://user-images.githubusercontent.com/61706378/81244446-26576580-901b-11ea-9055-b03070957ba7.png)
: install_deps.sh
